<#
.SYNOPSIS
Regenerates the timer icon catalog in Ui/Lucide.cs from Lucide's icon metadata.

.DESCRIPTION
Reads icons/*.json and categories/*.json from a checkout (or source archive) of the lucide-icons/lucide
repository at the tag that matches assets/fonts/lucide-<version>.ttf, and font/codepoints.json from the
lucide-static package of the same version. Every icon in one of -Categories is written, sorted by name,
between the BEGIN/END GENERATED markers of Ui/Lucide.cs; the rest of the file is left alone.

.EXAMPLE
curl.exe -L -o lucide.tgz https://codeload.github.com/lucide-icons/lucide/tar.gz/refs/tags/1.51.0
curl.exe -L -o static.tgz https://registry.npmjs.org/lucide-static/-/lucide-static-1.51.0.tgz
tar -xzf lucide.tgz; tar -xzf static.tgz
tools/lucide-catalog.ps1 -Repo lucide-1.51.0 -Static package
#>
param(
    [Parameter(Mandatory)][string]$Repo,
    [Parameter(Mandatory)][string]$Static,
    [string[]]$Categories = @('accessibility', 'animals', 'buildings', 'emoji', 'food-beverage', 'nature', 'navigation',
        'people', 'science', 'seasons', 'shapes', 'sustainability', 'tools', 'transportation', 'travel', 'weather')
)
$ErrorActionPreference = 'Stop'
$target = Join-Path $PSScriptRoot '..\Ui\Lucide.cs'

function Pascal([string]$slug) { -join ($slug -split '-' | ForEach-Object { $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1) }) }
function Quote([string]$text) { '"' + $text.Replace('\', '\\').Replace('"', '\"') + '"' }

$codepoints = Get-Content -Raw -Encoding UTF8 (Join-Path $Static 'font\codepoints.json') | ConvertFrom-Json
$version = (Get-Content -Raw -Encoding UTF8 (Join-Path $Static 'package.json') | ConvertFrom-Json).version
if (-not (Test-Path (Join-Path $PSScriptRoot "..\assets\fonts\lucide-$version.ttf"))) {
    throw "assets/fonts/lucide-$version.ttf not found; the catalog must match the embedded font."
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("    // Generated by tools/lucide-catalog.ps1 from lucide $version; do not edit by hand.")
$lines.Add('    [Flags]')
$lines.Add('    internal enum Category : ushort')
$lines.Add('    {')
for ($i = 0; $i -lt $Categories.Count; $i++) {
    $lines.Add("        $(Pascal $Categories[$i]) = 1 << $i,")
}
$lines.Add('    }')
$lines.Add('')
$lines.Add('    // lucide.dev category titles, in the order of Category.')
$titles = foreach ($slug in $Categories) {
    $category = Get-Content -Raw -Encoding UTF8 (Join-Path $Repo "categories\$slug.json") | ConvertFrom-Json
    "        (Category.$(Pascal $slug), $(Quote $category.title)),"
}
$lines.Add('    internal static readonly (Category Category, string Title)[] Categories =')
$lines.Add('    [')
foreach ($title in $titles) { $lines.Add($title) }
$lines.Add('    ];')
$lines.Add('')

$icons = foreach ($file in Get-ChildItem (Join-Path $Repo 'icons') -Filter *.json) {
    $meta = Get-Content -Raw -Encoding UTF8 $file.FullName | ConvertFrom-Json
    $selected = @($Categories | Where-Object { $meta.categories -contains $_ })
    if ($selected.Count -eq 0) { continue }
    $name = $file.BaseName
    $codepoint = $codepoints.$name
    if ($null -eq $codepoint) { throw "$name has no codepoint in lucide-static $version." }
    if ($codepoint -gt 0xFFFF) { throw "$name is outside the BMP; Lucide.Icon stores one UTF-16 unit." }
    [pscustomobject]@{ Name = $name; Codepoint = [int]$codepoint; Categories = ($selected | ForEach-Object { "Category.$(Pascal $_)" }) -join ' | ' }
}
# Lucide.Find uses an ordinal binary search.
$byName = @{}
foreach ($icon in $icons) { $byName[$icon.Name] = $icon }
$keys = [string[]]@($icons | ForEach-Object Name)
[Array]::Sort($keys, [StringComparer]::Ordinal)
$icons = @($keys | ForEach-Object { $byName[$_] })

$lines.Add("    // $($icons.Count) icons, sorted by name (ordinal).")
$lines.Add('    internal static readonly Icon[] Icons =')
$lines.Add('    [')
foreach ($icon in $icons) {
    $lines.Add("        new($(Quote $icon.Name), '\u$($icon.Codepoint.ToString('X4'))', $($icon.Categories)),")
}
$lines.Add('    ];')

$source = [IO.File]::ReadAllText($target)
$begin = '    // BEGIN GENERATED'
$end = '    // END GENERATED'
$start = $source.IndexOf($begin)
$stop = $source.IndexOf($end)
if ($start -lt 0 -or $stop -lt $start) { throw "Ui/Lucide.cs has no generated region." }
$start = $source.IndexOf("`n", $start) + 1
$newline = if ($source.Contains("`r`n")) { "`r`n" } else { "`n" }
$generated = ($lines -join $newline) + $newline
[IO.File]::WriteAllText($target, $source.Substring(0, $start) + $generated + $source.Substring($stop), (New-Object Text.UTF8Encoding $false))
Write-Host "Wrote $($icons.Count) icons in $($Categories.Count) categories to Ui/Lucide.cs."
